baseURL = "https://thurnix.com"
languageCode = "vi-VN"
title = "Thurnix"
description = "Thurnix cung cấp dịch vụ SEO chuyên nghiệp, thiết kế web chuẩn SEO và dịch vụ AEO tại Việt Nam. Đưa website lên TOP Google với công nghệ AI tiên tiến."

# Theme Config
theme = "../.."

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

# Enable taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Pagination
paginate = 6
paginatePath = "page"

[params]
  description = "Thurnix là công ty SEO uy tín tại Việt Nam, cung cấp các giải pháp tối ưu công cụ tìm kiếm chuyên nghiệp, giúp website doanh nghiệp tăng traffic nhanh."
  author = "Thurnix SEO"
  logo = "/images/thurnix.webp"
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  # googleAnalytics = "G-XXXXXXXXXX"

  # Global CTA Configuration
  [params.cta]
    enable = true
    title = "Ready to Build Your SaaS Website?"
    description = "Join companies already using our theme to create beautiful, high-performance websites."
    gradient_from = "#2563eb"  # Indigo-600
    gradient_to = "#7c3aed"    # Purple-600
    gradient_angle = 30
    [params.cta.primary_button]
      text = "Get Started Free"
      url = "/get-started"
    [params.cta.secondary_button]
      text = "Book Demo"
      url = "/demo"
  
  # Social Media Links
  [params.social]
    linkedin = "https://linkedin.com/in/thurnixseo"
    twitter = "https://twitter.com/thurnixseo"
    youtube = "https://youtube.com/@thurnixseo"
    facebook = "https://facebook.com/thurnixseo"
    instagram = "https://instagram.com/thurnixseo"
    github = "https://github.com/thurnixseo"
  
  # Footer Configuration
  [params.footer]
    column_1_title = "Dịch Vụ"
    column_2_title = "Thông tin"
    column_3_title = "Chính sách"
  
  [params.header]
    # Header background and border styles (optional)
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Logo configuration
    [params.header.logo]
      src = "/images/thurnix.webp"
    
    # Menu configuration
    [params.header.menu]
      spacing = "space-x-8"
      
      # Dropdown menu configuration
      [params.header.menu.dropdown]
        width = "w-72"
        container_padding = "py-6"
        item_padding = "px-8 py-3"
        background = "bg-white"
        border = "border border-gray-100"
        shadow = "shadow-xl"
        radius = "rounded-lg"
        text_color = "text-gray-700"
        hover_background = "hover:bg-gray-50"
        text_size = "text-sm"
    
    # Button configuration  
      # Get Started button
      [params.header.buttons.getStarted]
        text = "YÊU CẦU BÁO GIÁ"
        url = "/yeu-cau-bao-gia/"

  # Blog configuration
  [params.blog]
    enable = true
    title = "Thurnix's Blog"
    subtitle = "Các bài viết thuộc lĩnh vực: Tin dịch vụ, kiến thức SEO, kiến thức AEO, Kiến thức thiết kế web chuẩn SEO."
    
    # Blog CTA configuration
    [params.blog.cta]
      enable = true  # Enable/disable CTA in blog posts
    
    # Sidebar configuration
    [params.blog.sidebar]
      # Recent articles section
      [params.blog.sidebar.recent]
        enable = true
        title = "Bài viết mới"
        count = 5
      
      # Categories section
      [params.blog.sidebar.categories]
        enable = true
        title = "Danh mục"
      
      # Tags section
      [params.blog.sidebar.tags]
        enable = true
        title = "Tags Phổ Biến"
        count = 20

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[build]
  writeStats = true

[build.buildStats]
  enable = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']
  
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Navigation Menu
[menu]
  [[menu.main]]
    name = "Dịch vụ"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Dịch vụ SEO", url = "/dich-vu-seo" },
        { name = "Dịch vụ AEO", url = "/dich-vu-aeo" },
        { name = "Thiết kế web chuẩn SEO", url = "/thiet-ke-web-chuan-seo" }
      ]
  [[menu.main]]
    name = "Về Thurnix"
    url = "/gioi-thieu"
    weight = 2
  [[menu.main]]
    name = "Bảng giá dịch vụ"
    url = "/bang-gia"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4
  [[menu.main]]
  name = "Liên hệ"
  url = "/lien-he"
  weight = 5

  # Footer Column 1 Menu
  [[menu.footer_column_1]]
    name = "Dịch vụ SEO"
    url = "/dich-vu-seo"
    weight = 1
  [[menu.footer_column_1]]
    name = "Dịch vụ AEO"
    url = "/dich-vu-aeo"
    weight = 2
  [[menu.footer_column_1]]
    name = "Thiết kế web chuẩn SEO"
    url = "/thiet-ke-web-chuan-seo"
    weight = 3

  # Footer Column 2 Menu
  [[menu.footer_column_2]]
    name = "Blog Thurnix"
    url = "/blog"
    weight = 1
  [[menu.footer_column_2]]
    name = "Về Thurnix"
    url = "/gioi-thieu"
    weight = 2
  [[menu.footer_column_2]]
    name = "Tuyển dụng"
    url = "/tuyen-dung"
    weight = 3

  # Footer Column 3 Menu
  [[menu.footer_column_3]]
    name = "Điều khoản & Điều kiện"
    url = "/dieu-khoan-dieu-kien"
    weight = 1
  [[menu.footer_column_3]]
    name = "Chính sách bảo mật"
    url = "/chinh-sach-bao-mat"
    weight = 2
  [[menu.footer_column_3]]
    name = "Liên hệ Thurnix"
    url = "/lien-he"
    weight = 3
