[build]
command = "curl -L https://github.com/gohugoio/hugo/releases/download/v0.147.6/hugo_extended_0.147.6_Linux-64bit.tar.gz | tar -xz && ./hugo --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.147.6"